"""Add user bio for AI

Revision ID: 6b8fab394dfa
Revises: e6f06f36caef
Create Date: 2026-04-18 19:38:02.977588
"""
from alembic import op
import sqlalchemy as sa


revision = '6b8fab394dfa'
down_revision = 'e6f06f36caef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
