"""Add parent_concept_id for multi_fsrs

Revision ID: e6f06f36caef
Revises: e9e1488a4866
Create Date: 2026-04-14 23:09:34.877090
"""
from alembic import op
import sqlalchemy as sa


revision = 'e6f06f36caef'
down_revision = 'e9e1488a4866'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('parent_concept_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'concepts', 'concepts', ['parent_concept_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'concepts', type_='foreignkey')
    op.drop_column('concepts', 'parent_concept_id')
    # ### end Alembic commands ###
